version: '3'
services:
  postgres:
    image: 'khanhreactdocker.azurecr.io/samples/postgres'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'khanhreactdocker.azurecr.io/samples/postgres'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    image: 'khanhreactdocker.azurecr.io/react-docker-nginx'
    ports:
      - '3050:80'
  api:
    image: 'khanhreactdocker.azurecr.io/react-docker-server'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  worker:
    image: 'khanhreactdocker.azurecr.io/react-docker-worker'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
