version: '3'
services:
  postgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:alpine'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    image: 'kkhanhluu/docker-react-nginx:latest'
    ports:
      - '3050:80'
  api:
    image: 'kkhanhluu/docker-react-server:main'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    image: 'kkhanhluu/docker-react-frontend:main'
  worker:
    image: 'kkhanhluu/docker-react-worker:main'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
