apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: kkhanhluu/docker-react-frontend:main
      ports:
        - containerPort: 3000
