# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker images

on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for frontend image
        id: metaFrontend
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: kkhanhluu/docker-react-frontend
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.metaFrontend.outputs.tags }}
          labels: ${{ steps.metaFrontend.outputs.labels }}

      - name: Extract metadata (tags, labels) for backend image
        id: metaServer
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: kkhanhluu/docker-react-server
      - name: Build and push backend Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./server
          push: true
          tags: ${{ steps.metaServer.outputs.tags }}
          labels: ${{ steps.metaServer.outputs.labels }}

      - name: Extract metadata (tags, labels) for worker image
        id: metaWorker
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: kkhanhluu/docker-react-worker
      - name: Build and push worker Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./worker
          push: true
          tags: ${{ steps.metaWorker.outputs.tags }}
          labels: ${{ steps.metaWorker.outputs.labels }}
